volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:11.7
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: unless-stopped
  mailer:
    image: meteopavel/legacy_django_mailer-mailer
    restart: unless-stopped
    env_file: .env
    volumes: 
      - static:/static
    depends_on:
      - db
      - redis
  celery:
    image: meteopavel/legacy_django_mailer-celery
    restart: unless-stopped
    command: celery -A mailer worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
  gateway:
    image: meteopavel/legacy_django_mailer-gateway
    restart: unless-stopped
    env_file: .env 
    ports:
      - 8111:80 
    volumes: 
      - static:/static
    depends_on:
      - mailer