volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:11.7
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
  mailer:
    build: ./mailer/
    env_file: .env
    volumes: 
      - static:/static
    depends_on:
      - db
      - redis
  celery:
    build: ./mailer/
    command: celery -A mailer worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
  gateway:
    build: ./gateway/
    env_file: .env 
    ports:
      - 8111:80 
    volumes: 
      - static:/static
    depends_on:
      - mailer